### ISSUE TITLE
What is the rust kernel workflow?

### ISSUE THREAD

**Issue by aionick** [aionnetwork/node_test_harness#24]
We need to figure out how to do the following things with the rust kernel so that we can determine how our current setup needs to be modified in order to support a rust node:
- build the kernel
- start the kernel
- stop the kernel

Some other things we may be interested in are the kernel's database, where its log files are stored, and what kind of config options exist.

**Comment by aionick** [comment]
Maybe we could get @aion-kelvin to write up a quick few sentences about this, so that it's general knowledge and here for everyone (since he worked on this), but otherwise this has been answered.

**Comment by aion-kelvin** [comment]
Initial implementation -- https://github.com/aionnetwork/node_test_harness/commit/f19377fcbcfb02c3a949426376915cd93606ca22

> build the kernel 

Not supported in this implementation; the direction of our usage of test harness is away from having the test harness building the kernel

> Start the kernel

Starting the Rust kernel is similar to starting the Java kernel -- you launch a process.  The main difference is that in order to do meaningful testing with Rust kernel, you need to also start and attach an external miner to the kernel because it lacks a built-in miner.  See commit above for how this is done.

> stop the kernel

Kill the started process of the Rust kernel.  And also the miner.
